name: 'test-container'

on: [pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: 'Test pull request'
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - 
        name: Build and export to Docker
        uses: docker/build-push-action@v5.3.0
        with:
          load: true
          tags: molecule-test
      - 
        name: Test image
        run: |
          docker run --rm molecule-test --version